package service

import (
	"context"
	"fmt"
	"time"

	"hris-backend/internal/repository"
	"hris-backend/internal/struct/dto"
	"hris-backend/internal/struct/model"
)

type BusinessTripService interface {
	GetAll(ctx context.Context, params dto.BusinessTripListParams) ([]dto.BusinessTripRequestResponse, error)
	GetByID(ctx context.Context, id uint) (dto.BusinessTripRequestResponse, error)
	Create(ctx context.Context, employeeID uint, req dto.CreateBusinessTripRequest) (dto.BusinessTripRequestResponse, error)
	UpdateStatus(ctx context.Context, employeeID uint, id uint, req dto.UpdateBusinessTripStatusRequest) (dto.BusinessTripRequestResponse, error)
	Delete(ctx context.Context, id uint) error
}

type businessTripService struct {
	repo       repository.BusinessTripRepository
	attendRepo repository.AttendanceRepository
	txManager  repository.TxManager
}

func NewBusinessTripService(
	repo repository.BusinessTripRepository,
	attendRepo repository.AttendanceRepository,
	txManager repository.TxManager,
) BusinessTripService {
	return &businessTripService{
		repo:       repo,
		attendRepo: attendRepo,
		txManager:  txManager,
	}
}

func (s *businessTripService) GetAll(ctx context.Context, params dto.BusinessTripListParams) ([]dto.BusinessTripRequestResponse, error) {
	return s.repo.GetAll(ctx, nil, params)
}

func (s *businessTripService) GetByID(ctx context.Context, id uint) (dto.BusinessTripRequestResponse, error) {
	res, err := s.repo.GetByID(ctx, nil, id)
	if err != nil {
		return dto.BusinessTripRequestResponse{}, err
	}
	return *res, nil
}

func (s *businessTripService) Create(ctx context.Context, employeeID uint, req dto.CreateBusinessTripRequest) (dto.BusinessTripRequestResponse, error) {
	sDate, err1 := time.Parse("2006-01-02", req.StartDate)
	eDate, err2 := time.Parse("2006-01-02", req.EndDate)
	if err1 != nil || err2 != nil {
		return dto.BusinessTripRequestResponse{}, fmt.Errorf("invalid date format")
	}

	m := model.BusinessTripRequest{
		EmployeeID:  employeeID,
		StartDate:   sDate,
		EndDate:     eDate,
		Destination: req.Destination,
		Purpose:     req.Purpose,
		DocumentURL: req.DocumentURL,
		Status:      "pending",
	}

	created, err := s.repo.Create(ctx, nil, m)
	if err != nil {
		return dto.BusinessTripRequestResponse{}, err
	}

	return s.GetByID(ctx, created.ID)
}

func (s *businessTripService) UpdateStatus(ctx context.Context, employeeID uint, id uint, req dto.UpdateBusinessTripStatusRequest) (dto.BusinessTripRequestResponse, error) {
	trip, err := s.repo.GetByID(ctx, nil, id)
	if err != nil {
		return dto.BusinessTripRequestResponse{}, err
	}
	if trip.Status != "pending" {
		return dto.BusinessTripRequestResponse{}, fmt.Errorf("request is no longer pending")
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return dto.BusinessTripRequestResponse{}, err
	}
	defer tx.Rollback()

	if err := s.repo.UpdateStatus(ctx, tx, id, req.Status, employeeID, req.Notes); err != nil {
		return dto.BusinessTripRequestResponse{}, err
	}

	if req.Status == "approved" {
		// sync attendance log
		sDate, _ := time.Parse("2006-01-02", trip.StartDate)
		eDate, _ := time.Parse("2006-01-02", trip.EndDate)

		for d := sDate; !d.After(eDate); d = d.AddDate(0, 0, 1) {
			dateStr := d.Format("2006-01-02")
			log, _ := s.attendRepo.GetTodayLog(ctx, tx, trip.EmployeeID, dateStr)
			if log != nil {
				upd := map[string]interface{}{
					"status":                   string(model.AttendanceBusinessTrip),
					"business_trip_request_id": id,
					"is_counted_as_full_day":   true,
					"late_minutes":             0,
					"early_leave_minutes":      0,
				}
				s.attendRepo.UpdateLog(ctx, tx, log.ID, upd)
			} else {
				cm := model.ClockMethodManual
				newLog := model.AttendanceLog{
					EmployeeID:            trip.EmployeeID,
					AttendanceDate:        d,
					Status:                model.AttendanceBusinessTrip,
					BusinessTripRequestID: &id,
					IsCountedAsFullDay:    true,
					IsAutoGenerated:       true,
					ClockInMethod:         &cm,
					ClockOutMethod:        &cm,
				}
				s.attendRepo.CreateLog(ctx, tx, newLog)
			}
		}
	}

	if err := tx.Commit(); err != nil {
		return dto.BusinessTripRequestResponse{}, err
	}

	return s.GetByID(ctx, id)
}

func (s *businessTripService) Delete(ctx context.Context, id uint) error {
	trip, err := s.repo.GetByID(ctx, nil, id)
	if err != nil {
		return err
	}
	if trip.Status != "pending" {
		return fmt.Errorf("cannot delete processed business trip request")
	}
	return s.repo.Delete(ctx, nil, id)
}
