package service

import (
	"context"
	"fmt"
	"time"

	"hris-backend/internal/repository"
	"hris-backend/internal/struct/dto"
	"hris-backend/internal/struct/model"
)

type DailyReportService interface {
	GetAll(ctx context.Context, params dto.DailyReportListParams) ([]dto.DailyReportResponse, error)
	GetByID(ctx context.Context, id uint) (dto.DailyReportResponse, error)
	Create(ctx context.Context, employeeID uint, req dto.CreateDailyReportRequest) (dto.DailyReportResponse, error)
	Update(ctx context.Context, id uint, employeeID uint, req dto.UpdateDailyReportRequest) (dto.DailyReportResponse, error) // ADDED
	Delete(ctx context.Context, id uint) error
}

type dailyReportService struct {
	repo repository.DailyReportRepository
}

func NewDailyReportService(repo repository.DailyReportRepository) DailyReportService {
	return &dailyReportService{repo: repo}
}

func (s *dailyReportService) GetAll(ctx context.Context, params dto.DailyReportListParams) ([]dto.DailyReportResponse, error) {
	return s.repo.GetAll(ctx, nil, params)
}

func (s *dailyReportService) GetByID(ctx context.Context, id uint) (dto.DailyReportResponse, error) {
	res, err := s.repo.GetByID(ctx, nil, id)
	if err != nil {
		return dto.DailyReportResponse{}, err
	}
	return *res, nil
}

func (s *dailyReportService) Create(ctx context.Context, employeeID uint, req dto.CreateDailyReportRequest) (dto.DailyReportResponse, error) {
	d, err := time.Parse("2006-01-02", req.ReportDate)
	if err != nil {
		return dto.DailyReportResponse{}, fmt.Errorf("invalid date format")
	}

	attendanceLogID := uint(0)
	if req.AttendanceLogID != nil {
		attendanceLogID = *req.AttendanceLogID
	}

	now := time.Now()
	m := model.DailyReport{
		EmployeeID:      employeeID,
		ReportDate:      d,
		Activities:      &req.Activities,
		IsSubmitted:     true,
		SubmittedAt:     &now,
		IsAutoGenerated: false,
		AttendanceLogID: attendanceLogID,
	}

	created, err := s.repo.Create(ctx, nil, m)
	if err != nil {
		return dto.DailyReportResponse{}, err
	}

	return s.GetByID(ctx, created.ID)
}

func (s *dailyReportService) Update(ctx context.Context, id uint, employeeID uint, req dto.UpdateDailyReportRequest) (dto.DailyReportResponse, error) {
	existing, err := s.repo.GetByID(ctx, nil, id)
	if err != nil {
		return dto.DailyReportResponse{}, fmt.Errorf("daily report not found: %w", err)
	}

	updates := map[string]interface{}{
		"updated_at": time.Now(),
	}

	if req.Activities != nil {
		updates["activities"] = req.Activities
		// If updating activities, mark as submitted
		now := time.Now()
		updates["is_submitted"] = true
		updates["submitted_at"] = now
	}

	_ = existing // validate ownership if needed

	if err := s.repo.Update(ctx, nil, id, updates); err != nil {
		return dto.DailyReportResponse{}, fmt.Errorf("update daily report: %w", err)
	}

	return s.GetByID(ctx, id)
}

func (s *dailyReportService) Delete(ctx context.Context, id uint) error {
	return s.repo.Delete(ctx, nil, id)
}
