package service

import (
	"context"
	"fmt"
	"time"

	"hris-backend/internal/repository"
	"hris-backend/internal/struct/dto"
	"hris-backend/internal/struct/model"
	"hris-backend/internal/utils"
)

type MutabaahService interface {
	GetTodayStatus(ctx context.Context, employeeID uint) (dto.MutabaahTodayResponse, error)
	Submit(ctx context.Context, employeeID uint, isTrainer bool, req dto.MutabaahSubmitRequest) (dto.MutabaahLogResponse, error)
	Cancel(ctx context.Context, employeeID uint, req dto.MutabaahCancelRequest) (dto.MutabaahLogResponse, error)
	GetAllLogs(ctx context.Context, params dto.MutabaahListParams) ([]dto.MutabaahLogResponse, error)
	HRDCancel(ctx context.Context, id uint) (dto.MutabaahLogResponse, error)
	GetDailyReport(ctx context.Context, date string) ([]dto.MutabaahDailyReport, error)
	GetMonthlyReport(ctx context.Context, month, year int) ([]dto.MutabaahMonthlySummary, error)
	GetCategoryReport(ctx context.Context, date string) ([]dto.MutabaahCategorySummary, error)
}

type mutabaahService struct {
	repo       repository.MutabaahRepository
	attendRepo repository.AttendanceRepository
	txManager  repository.TxManager
}

func NewMutabaahService(
	repo repository.MutabaahRepository,
	attendRepo repository.AttendanceRepository,
	txManager repository.TxManager,
) MutabaahService {
	return &mutabaahService{
		repo:       repo,
		attendRepo: attendRepo,
		txManager:  txManager,
	}
}

func (s *mutabaahService) GetTodayStatus(ctx context.Context, employeeID uint) (dto.MutabaahTodayResponse, error) {
	today := utils.TodayDate()

	log, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahTodayResponse{}, fmt.Errorf("get today mutabaah: %w", err)
	}

	attendLog, _ := s.attendRepo.GetTodayLog(ctx, nil, employeeID, today)

	canSubmit := false
	canCancel := false
	reason := ""

	if log == nil {
		canSubmit = true
	} else if log.IsSubmitted {
		canCancel = true
	} else {
		canSubmit = true
	}

	return dto.MutabaahTodayResponse{
		Log:          log,
		CanSubmit:    canSubmit,
		CanCancel:    canCancel,
		IsWorkingDay: attendLog != nil,
		Reason:       reason,
	}, nil
}

func (s *mutabaahService) Submit(ctx context.Context, employeeID uint, isTrainer bool, req dto.MutabaahSubmitRequest) (dto.MutabaahLogResponse, error) {
	today := utils.TodayDate()
	now := time.Now()

	if req.AttendanceLogID == 0 {
		return dto.MutabaahLogResponse{}, fmt.Errorf("attendance_log_id is required")
	}

	existing, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get mutabaah log: %w", err)
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()

	var resultID uint

	if existing == nil {
		targetPages := 5
		if isTrainer {
			targetPages = 10
		}
		logModel := model.MutabaahLog{
			EmployeeID:      employeeID,
			AttendanceLogID: req.AttendanceLogID,
			LogDate:         now,
			TargetPages:     targetPages,
			IsSubmitted:     true,
			SubmittedAt:     &now,
			IsAutoGenerated: false,
		}
		created, err := s.repo.CreateLog(ctx, tx, logModel)
		if err != nil {
			return dto.MutabaahLogResponse{}, fmt.Errorf("create mutabaah: %w", err)
		}
		resultID = created.ID
	} else {
		if existing.IsSubmitted {
			return dto.MutabaahLogResponse{}, fmt.Errorf("mutabaah hari ini sudah disubmit, batalkan terlebih dahulu jika ingin mengubah")
		}

		err = s.repo.UpdateLog(ctx, tx, existing.ID, map[string]interface{}{
			"attendance_log_id": req.AttendanceLogID,
			"is_submitted":      true,
			"submitted_at":      now,
			"updated_at":        now,
		})
		if err != nil {
			return dto.MutabaahLogResponse{}, fmt.Errorf("update mutabaah: %w", err)
		}
		resultID = existing.ID
	}

	if err := tx.Commit(); err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("commit: %w", err)
	}

	result, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil || result == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get result: %w", err)
	}
	_ = resultID
	return *result, nil
}

func (s *mutabaahService) Cancel(ctx context.Context, employeeID uint, req dto.MutabaahCancelRequest) (dto.MutabaahLogResponse, error) {
	today := utils.TodayDate()
	now := time.Now()

	existing, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get mutabaah log: %w", err)
	}
	if existing == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("tidak ada mutabaah yang bisa dibatalkan hari ini")
	}
	if !existing.IsSubmitted {
		return dto.MutabaahLogResponse{}, fmt.Errorf("mutabaah hari ini belum disubmit")
	}

	if req.MutabaahLogID != 0 && existing.ID != req.MutabaahLogID {
		return dto.MutabaahLogResponse{}, fmt.Errorf("mutabaah log ID tidak sesuai")
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()

	err = s.repo.UpdateLog(ctx, tx, existing.ID, map[string]interface{}{
		"is_submitted": false,
		"submitted_at": nil,
		"updated_at":   now,
	})
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("cancel mutabaah: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("commit: %w", err)
	}

	result, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil || result == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get result: %w", err)
	}
	return *result, nil
}

func (s *mutabaahService) GetAllLogs(ctx context.Context, params dto.MutabaahListParams) ([]dto.MutabaahLogResponse, error) {
	return s.repo.GetAllLogs(ctx, nil, params)
}

func (s *mutabaahService) HRDCancel(ctx context.Context, id uint) (dto.MutabaahLogResponse, error) {
	now := time.Now()

	err := s.repo.UpdateLog(ctx, nil, id, map[string]interface{}{
		"is_submitted": false,
		"submitted_at": nil,
		"updated_at":   now,
	})
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("hrd cancel mutabaah: %w", err)
	}

	result, err := s.repo.GetByID(ctx, nil, id)
	if err != nil || result == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get result: %w", err)
	}
	return *result, nil
}

func (s *mutabaahService) GetDailyReport(ctx context.Context, date string) ([]dto.MutabaahDailyReport, error) {
	return s.repo.GetDailyReport(ctx, nil, date)
}

func (s *mutabaahService) GetMonthlyReport(ctx context.Context, month, year int) ([]dto.MutabaahMonthlySummary, error) {
	return s.repo.GetMonthlyReport(ctx, nil, month, year)
}

func (s *mutabaahService) GetCategoryReport(ctx context.Context, date string) ([]dto.MutabaahCategorySummary, error) {
	return s.repo.GetCategoryReport(ctx, nil, date)
}
