package service

import (
	"context"
	"fmt"
	"time"

	"hris-backend/internal/repository"
	"hris-backend/internal/struct/dto"
	"hris-backend/internal/struct/model"
	"hris-backend/internal/utils"
)

type MutabaahService interface {
	GetTodayStatus(ctx context.Context, employeeID uint) (dto.MutabaahTodayResponse, error)
	Submit(ctx context.Context, employeeID uint, req dto.MutabaahSubmitRequest) (dto.MutabaahLogResponse, error)
	Cancel(ctx context.Context, employeeID uint) (dto.MutabaahLogResponse, error)
	GetAllLogs(ctx context.Context, params dto.MutabaahListParams) ([]dto.MutabaahLogResponse, error)
	HRDCancel(ctx context.Context, id uint) (dto.MutabaahLogResponse, error)
}

type mutabaahService struct {
	repo         repository.MutabaahRepository
	attendRepo   repository.AttendanceRepository
	txManager    repository.TxManager
}

func NewMutabaahService(
	repo repository.MutabaahRepository,
	attendRepo repository.AttendanceRepository,
	txManager repository.TxManager,
) MutabaahService {
	return &mutabaahService{
		repo:       repo,
		attendRepo: attendRepo,
		txManager:  txManager,
	}
}

// ─── Today Status ─────────────────────────────────────────────────────────────

func (s *mutabaahService) GetTodayStatus(ctx context.Context, employeeID uint) (dto.MutabaahTodayResponse, error) {
	today := utils.TodayDate()

	log, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahTodayResponse{}, fmt.Errorf("get today mutabaah: %w", err)
	}

	// Cek apakah hari kerja (ada attendance log present/late)
	attendLog, err := s.attendRepo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahTodayResponse{}, fmt.Errorf("get today attendance: %w", err)
	}

	isWorkingDay := attendLog != nil &&
		(attendLog.Status == string(model.AttendancePresent) ||
			attendLog.Status == string(model.AttendanceLate) ||
			attendLog.Status == string(model.AttendanceBusinessTrip))

	canSubmit := false
	canCancel := false
	reason := ""

	if !isWorkingDay {
		reason = "hanya bisa submit mutabaah pada hari kerja setelah clock in"
	} else if log == nil {
		canSubmit = true
	} else if log.IsSubmitted {
		canCancel = true
	} else {
		// log ada tapi belum submit (auto-generated missing)
		canSubmit = true
	}

	return dto.MutabaahTodayResponse{
		Log:          log,
		CanSubmit:    canSubmit,
		CanCancel:    canCancel,
		IsWorkingDay: isWorkingDay,
		Reason:       reason,
	}, nil
}

// ─── Submit ───────────────────────────────────────────────────────────────────

func (s *mutabaahService) Submit(ctx context.Context, employeeID uint, req dto.MutabaahSubmitRequest) (dto.MutabaahLogResponse, error) {
	today := utils.TodayDate()
	now := time.Now()

	if req.Pages < 0 {
		return dto.MutabaahLogResponse{}, fmt.Errorf("jumlah halaman tidak boleh negatif")
	}

	// 1. Validasi attendance hari ini
	attendLog, err := s.attendRepo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get attendance log: %w", err)
	}
	if attendLog == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("anda belum melakukan clock in hari ini")
	}
	if attendLog.Status != string(model.AttendancePresent) &&
		attendLog.Status != string(model.AttendanceLate) &&
		attendLog.Status != string(model.AttendanceBusinessTrip) {
		return dto.MutabaahLogResponse{}, fmt.Errorf("mutabaah hanya bisa disubmit pada hari kerja")
	}

	// 2. Cek sudah submit belum
	existing, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get mutabaah log: %w", err)
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()

	var resultID uint

	if existing == nil {
		// Belum ada record — buat baru
		logModel := model.MutabaahLog{
			EmployeeID:      employeeID,
			AttendanceLogID: attendLog.ID,
			LogDate:         now,
			TargetPages:     req.Pages,
			IsSubmitted:     true,
			SubmittedAt:     &now,
			IsAutoGenerated: false,
		}
		created, err := s.repo.CreateLog(ctx, tx, logModel)
		if err != nil {
			return dto.MutabaahLogResponse{}, fmt.Errorf("create mutabaah: %w", err)
		}
		resultID = created.ID
	} else {
		if existing.IsSubmitted {
			return dto.MutabaahLogResponse{}, fmt.Errorf("mutabaah hari ini sudah disubmit, batalkan terlebih dahulu jika ingin mengubah")
		}
		// Ada record auto-generated (missing) — update
		err = s.repo.UpdateLog(ctx, tx, existing.ID, map[string]interface{}{
			"target_pages": req.Pages,
			"is_submitted": true,
			"submitted_at": now,
			"updated_at":   now,
		})
		if err != nil {
			return dto.MutabaahLogResponse{}, fmt.Errorf("update mutabaah: %w", err)
		}
		resultID = existing.ID
	}

	if err := tx.Commit(); err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("commit: %w", err)
	}

	result, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil || result == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get result: %w", err)
	}
	_ = resultID
	return *result, nil
}

// ─── Cancel ───────────────────────────────────────────────────────────────────

func (s *mutabaahService) Cancel(ctx context.Context, employeeID uint) (dto.MutabaahLogResponse, error) {
	today := utils.TodayDate()
	now := time.Now()

	existing, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get mutabaah log: %w", err)
	}
	if existing == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("tidak ada mutabaah yang bisa dibatalkan hari ini")
	}
	if !existing.IsSubmitted {
		return dto.MutabaahLogResponse{}, fmt.Errorf("mutabaah hari ini belum disubmit")
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()

	err = s.repo.UpdateLog(ctx, tx, existing.ID, map[string]interface{}{
		"target_pages": 0,
		"is_submitted": false,
		"submitted_at": nil,
		"updated_at":   now,
	})
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("cancel mutabaah: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("commit: %w", err)
	}

	result, err := s.repo.GetTodayLog(ctx, nil, employeeID, today)
	if err != nil || result == nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("get result: %w", err)
	}
	return *result, nil
}

// ─── List ─────────────────────────────────────────────────────────────────────

func (s *mutabaahService) GetAllLogs(ctx context.Context, params dto.MutabaahListParams) ([]dto.MutabaahLogResponse, error) {
	return s.repo.GetAllLogs(ctx, nil, params)
}

// ─── HRD Cancel ───────────────────────────────────────────────────────────────

func (s *mutabaahService) HRDCancel(ctx context.Context, id uint) (dto.MutabaahLogResponse, error) {
	now := time.Now()
	
	err := s.repo.UpdateLog(ctx, nil, id, map[string]interface{}{
		"target_pages": 0,
		"is_submitted": false,
		"submitted_at": nil,
		"updated_at":   now,
	})
	if err != nil {
		return dto.MutabaahLogResponse{}, fmt.Errorf("hrd cancel mutabaah: %w", err)
	}

	// fetch updated
	// need better GetByID in repo, but wait, MutabaahRepository doesn't have GetByID.
	// Oh, I need to add GetByID to repo!
	return dto.MutabaahLogResponse{}, nil
}
