package dto

import "time"

// ─── Attendance ────────────────────────────────────────────────────────────────

// PresignRequest — minta presigned URL sebelum upload foto
type AttendancePresignRequest struct {
	Action string `json:"action"` // "clock_in" | "clock_out"
}

type AttendancePresignResponse struct {
	UploadURL  string `json:"upload_url"`  // PUT ke sini
	ObjectKey  string `json:"object_key"`  // simpan, kirim saat submit
	ExpiresIn  int    `json:"expires_in"`  // detik
}

// ClockIn
type ClockInRequest struct {
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
	PhotoKey   string  `json:"photo_key"` // object_key dari presign
}

// ClockOut
type ClockOutRequest struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	PhotoKey  string  `json:"photo_key"`
}

// AttendanceLogResponse — response lengkap
type AttendanceLogResponse struct {
	ID                      uint       `json:"id"`
	EmployeeID              uint       `json:"employee_id"`
	EmployeeName            string     `json:"employee_name"`
	AttendanceDate          string     `json:"attendance_date"`
	ScheduleID              *uint      `json:"schedule_id"`
	ShiftName               *string    `json:"shift_name"`
	ClockInAt               *time.Time `json:"clock_in_at"`
	ClockOutAt              *time.Time `json:"clock_out_at"`
	ClockInPhotoURL         *string    `json:"clock_in_photo_url"`
	ClockOutPhotoURL        *string    `json:"clock_out_photo_url"`
	ClockInMethod           *string    `json:"clock_in_method"`
	ClockOutMethod          *string    `json:"clock_out_method"`
	Status                  string     `json:"status"`
	LateMinutes             int        `json:"late_minutes"`
	EarlyLeaveMinutes       int        `json:"early_leave_minutes"`
	OvertimeMinutes         int        `json:"overtime_minutes"`
	IsCountedAsFullDay      bool       `json:"is_counted_as_full_day"`
	PermissionRequestID     *uint      `json:"permission_request_id"`
	LeaveRequestID          *uint      `json:"leave_request_id"`
	BusinessTripRequestID   *uint      `json:"business_trip_request_id"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               *time.Time `json:"updated_at"`
}

// AttendanceTodayResponse — status presensi hari ini untuk pegawai
type AttendanceTodayResponse struct {
	Log              *AttendanceLogResponse `json:"log"`
	ShiftDetail      *ShiftDayContext       `json:"shift_detail"`      // info shift hari ini
	IsWorkingDay     bool                   `json:"is_working_day"`
	IsHoliday        bool                   `json:"is_holiday"`
	HolidayName      *string                `json:"holiday_name"`
	CanClockIn       bool                   `json:"can_clock_in"`
	CanClockOut      bool                   `json:"can_clock_out"`
	HasLeave         bool                   `json:"has_leave"`
	HasBusinessTrip  bool                   `json:"has_business_trip"`
	HasPermission    bool                   `json:"has_permission"`    // izin terlambat/pulang cepat
}

// ShiftDayContext — konteks shift untuk hari ini
type ShiftDayContext struct {
	ScheduleID      uint    `json:"schedule_id"`
	ShiftTemplateID uint    `json:"shift_template_id"`
	ShiftName       string  `json:"shift_name"`
	IsFlexible      bool    `json:"is_flexible"`
	DayOfWeek       string  `json:"day_of_week"`
	IsWorkingDay    bool    `json:"is_working_day"`
	ClockInStart    *string `json:"clock_in_start"`
	ClockInEnd      *string `json:"clock_in_end"`
	ClockOutStart   *string `json:"clock_out_start"`
	ClockOutEnd     *string `json:"clock_out_end"`
}

// AttendanceListParams — filter list presensi (admin)
type AttendanceListParams struct {
	EmployeeID *uint   `query:"employee_id"`
	DateFrom   *string `query:"date_from"`
	DateTo     *string `query:"date_to"`
	Status     *string `query:"status"`
}

// ─── Mutabaah ─────────────────────────────────────────────────────────────────

// MutabaahSubmitRequest — submit mutabaah hari ini
type MutabaahSubmitRequest struct {
	Pages int `json:"pages"` // jumlah halaman yang dibaca
}

type MutabaahLogResponse struct {
	ID              uint       `json:"id"`
	EmployeeID      uint       `json:"employee_id"`
	EmployeeName    string     `json:"employee_name"`
	LogDate         string     `json:"log_date"`
	TargetPages     int        `json:"target_pages"`
	IsSubmitted     bool       `json:"is_submitted"`
	SubmittedAt     *time.Time `json:"submitted_at"`
	IsAutoGenerated bool       `json:"is_auto_generated"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type MutabaahTodayResponse struct {
	Log          *MutabaahLogResponse `json:"log"`
	CanSubmit    bool                 `json:"can_submit"`
	CanCancel    bool                 `json:"can_cancel"`
	IsWorkingDay bool                 `json:"is_working_day"`
	Reason       string               `json:"reason,omitempty"` // alasan jika tidak bisa submit
}

type MutabaahListParams struct {
	EmployeeID  *uint   `query:"employee_id"`
	DateFrom    *string `query:"date_from"`
	DateTo      *string `query:"date_to"`
	IsSubmitted *bool   `query:"is_submitted"`
}

type MutabaahDailyReport struct {
	EmployeeID     uint    `json:"employee_id"`
	EmployeeName   string  `json:"employee_name"`
	EmployeeNumber string  `json:"employee_number"`
	DepartmentName *string `json:"department_name"`
	IsTrainer      bool    `json:"is_trainer"`
	TargetPages    int     `json:"target_pages"`
	IsSubmitted    bool    `json:"is_submitted"`
	SubmittedAt    *string `json:"submitted_at"`
}

type MutabaahMonthlySummary struct {
	EmployeeID           uint    `json:"employee_id"`
	EmployeeName         string  `json:"employee_name"`
	IsTrainer            bool    `json:"is_trainer"`
	TotalWorkingDays     int     `json:"total_working_days"`
	TotalSubmitted       int     `json:"total_submitted"`
	CompliancePercentage float64 `json:"compliance_percentage"`
}

type MutabaahCategorySummary struct {
	Category                 string  `json:"category"` // "trainer" | "non_trainer"
	TotalEmployees           int     `json:"total_employees"`
	TotalSubmittedToday      int     `json:"total_submitted_today"`
	TotalNotSubmittedToday   int     `json:"total_not_submitted_today"`
	AverageCompliance        float64 `json:"average_compliance"`
}
