package dto

import "time"

type DailyReportResponse struct {
	ID              uint       `json:"id"`
	EmployeeID      uint       `json:"employee_id"`
	EmployeeName    *string    `json:"employee_name"`
	AttendanceLogID *uint      `json:"attendance_log_id"`
	ReportDate      string     `json:"report_date"`
	Activities      *string    `json:"activities"`
	IsSubmitted     bool       `json:"is_submitted"`
	SubmittedAt     *time.Time `json:"submitted_at"`
	IsAutoGenerated bool       `json:"is_auto_generated"`
	Status          string     `json:"status"` // dynamically determined: submitted, pending, missing
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type CreateDailyReportRequest struct {
	ReportDate      string `json:"report_date"`
	Activities      string `json:"activities"`
	AttendanceLogID *uint  `json:"attendance_log_id"`
}

type UpdateDailyReportRequest struct {
	Activities *string `json:"activities"`
}

type DailyReportListParams struct {
	EmployeeID  *uint   `query:"employee_id"`
	StartDate   *string `query:"start_date"`
	EndDate     *string `query:"end_date"`
	IsSubmitted *bool   `query:"is_submitted"`
}
