package model

import (
	"time"

	"gorm.io/gorm"
)

type (
	ClockMethodEnum      string
	AttendanceStatusEnum string
)

const (
	ClockMethodFace   ClockMethodEnum = "face"
	ClockMethodManual ClockMethodEnum = "manual"
	ClockMethodQRCode ClockMethodEnum = "qr_code"
)

const (
	AttendancePresent      AttendanceStatusEnum = "present"
	AttendanceAbsent       AttendanceStatusEnum = "absent"
	AttendanceLate         AttendanceStatusEnum = "late"
	AttendancePermission   AttendanceStatusEnum = "permission"
	AttendanceLeave        AttendanceStatusEnum = "leave"
	AttendanceHoliday      AttendanceStatusEnum = "holiday"
	AttendanceBusinessTrip AttendanceStatusEnum = "business_trip"
)

type AttendanceLog struct {
	ID                    uint                 `gorm:"primaryKey;autoIncrement"                             json:"id"`
	EmployeeID            uint                 `gorm:"not null;index;uniqueIndex:uq_attendance"             json:"employee_id"`
	ScheduleID            *uint                `gorm:"index"                                                json:"schedule_id"`
	AttendanceDate        time.Time            `gorm:"type:date;not null;uniqueIndex:uq_attendance"         json:"attendance_date"`
	ClockInAt             *time.Time           `                                                            json:"clock_in_at"`
	ClockOutAt            *time.Time           `                                                            json:"clock_out_at"`
	ClockInLat            *float64             `gorm:"type:decimal(10,8)"                                  json:"clock_in_lat"`
	ClockInLng            *float64             `gorm:"type:decimal(11,8)"                                  json:"clock_in_lng"`
	ClockOutLat           *float64             `gorm:"type:decimal(10,8)"                                  json:"clock_out_lat"`
	ClockOutLng           *float64             `gorm:"type:decimal(11,8)"                                  json:"clock_out_lng"`
	ClockInPhotoURL       *string              `gorm:"type:text"                                           json:"clock_in_photo_url"`
	ClockOutPhotoURL      *string              `gorm:"type:text"                                           json:"clock_out_photo_url"`
	ClockInMethod         *ClockMethodEnum     `gorm:"type:clock_method_enum"                              json:"clock_in_method"`
	ClockOutMethod        *ClockMethodEnum     `gorm:"type:clock_method_enum"                              json:"clock_out_method"`
	Status                AttendanceStatusEnum `gorm:"type:attendance_status_enum;not null;default:absent" json:"status"`
	PermissionRequestID   *uint                `gorm:"index"                                               json:"permission_request_id"`
	LeaveRequestID        *uint                `gorm:"index"                                               json:"leave_request_id"`
	BusinessTripRequestID *uint                `gorm:"index"                                               json:"business_trip_request_id"`
	IsCountedAsFullDay    bool                 `gorm:"not null;default:false"                              json:"is_counted_as_full_day"`
	LateMinutes           int                  `gorm:"not null;default:0"                                  json:"late_minutes"`
	EarlyLeaveMinutes     int                  `gorm:"not null;default:0"                                  json:"early_leave_minutes"`
	LateNotes             *string              `gorm:"type:text"                                           json:"late_notes"`
	EarlyLeaveNotes       *string              `gorm:"type:text"                                           json:"early_leave_notes"`
	LateDocumentURL       *string              `gorm:"type:text"                                           json:"late_document_url"`
	OvertimeMinutes       int                  `gorm:"not null;default:0"                                  json:"overtime_minutes"`
	IsAutoGenerated       bool                 `gorm:"not null;default:false"                              json:"is_auto_generated"`
	CreatedAt             time.Time            `gorm:"not null;default:now()"                             json:"created_at"`
	UpdatedAt             *time.Time           `                                                           json:"updated_at"`
	DeletedAt             gorm.DeletedAt       `gorm:"index"                                               json:"deleted_at"`

	// Relations
	Employee            Employee             `gorm:"foreignKey:EmployeeID"            json:"employee,omitempty"`
	Schedule            *EmployeeSchedule    `gorm:"foreignKey:ScheduleID"            json:"schedule,omitempty"`
	PermissionRequest   *PermissionRequest   `gorm:"foreignKey:PermissionRequestID"   json:"permission_request,omitempty"`
	LeaveRequest        *LeaveRequest        `gorm:"foreignKey:LeaveRequestID"        json:"leave_request,omitempty"`
	BusinessTripRequest *BusinessTripRequest `gorm:"foreignKey:BusinessTripRequestID" json:"business_trip_request,omitempty"`
}
