package model

import (
	"time"

	"gorm.io/gorm"
)

type DailyReport struct {
	ID              uint           `gorm:"primaryKey;autoIncrement"                         json:"id"`
	EmployeeID      uint           `gorm:"not null;index;uniqueIndex:uq_daily_report"       json:"employee_id"`
	AttendanceLogID uint           `gorm:"not null;index"                                   json:"attendance_log_id"`
	ReportDate      time.Time      `gorm:"type:date;not null;uniqueIndex:uq_daily_report"   json:"report_date"`
	Activities      *string        `gorm:"type:text"                                        json:"activities"`
	IsSubmitted     bool           `gorm:"not null;default:false"                           json:"is_submitted"`
	SubmittedAt     *time.Time     `                                                        json:"submitted_at"`
	IsAutoGenerated bool           `gorm:"not null;default:false"                           json:"is_auto_generated"`
	CreatedAt       time.Time      `gorm:"not null;default:now()"                          json:"created_at"`
	UpdatedAt       *time.Time     `                                                        json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index"                                            json:"deleted_at"`

	// Relations
	Employee      Employee      `gorm:"foreignKey:EmployeeID"      json:"employee,omitempty"`
	AttendanceLog AttendanceLog `gorm:"foreignKey:AttendanceLogID" json:"attendance_log,omitempty"`
}
