package model

import (
	"time"

	"gorm.io/gorm"
)

type MutabaahLog struct {
	ID              uint           `gorm:"primaryKey;autoIncrement"                          json:"id"`
	EmployeeID      uint           `gorm:"not null;index;uniqueIndex:uq_mutabaah"            json:"employee_id"`
	AttendanceLogID uint           `gorm:"not null;index"                                    json:"attendance_log_id"`
	LogDate         time.Time      `gorm:"type:date;not null;uniqueIndex:uq_mutabaah"        json:"log_date"`
	TargetPages     int            `gorm:"not null"                                          json:"target_pages"`
	IsSubmitted     bool           `gorm:"not null;default:false"                            json:"is_submitted"`
	SubmittedAt     *time.Time     `                                                         json:"submitted_at"`
	IsAutoGenerated bool           `gorm:"not null;default:false"                            json:"is_auto_generated"`
	CreatedAt       time.Time      `gorm:"not null;default:now()"                           json:"created_at"`
	UpdatedAt       *time.Time     `                                                         json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index"                                             json:"deleted_at"`

	// Relations
	Employee      Employee      `gorm:"foreignKey:EmployeeID"      json:"employee,omitempty"`
	AttendanceLog AttendanceLog `gorm:"foreignKey:AttendanceLogID" json:"attendance_log,omitempty"`
}
